name    'ericsson-nisclient'
version '1.0.0'
source 'git://github.com/Ericsson/puppet-module-nisclient.git'
author 'Ericsson'
license 'Apache License, Version 2.0'
summary 'Manage the NIS client'
description 'Manage the NIS client'
project_page 'http://github.com/Ericsson/puppet-module-nisclient'

dependency 'ghoneycutt/rpcbind', '>= 1.1.0'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
